_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "output/R50/150k_tt_mlt_13_15_textocr/finetune/totaltext/model_0004999.pth"
  POST_PROCESS:
    ENABLED: True # Set to True to use the LM post-processor with beam search
    LM_PATH: "/home/kylee/DeepSolo/character_lm_enriched_5g.binary" # Path relative to where you run the script, or absolute path
    LM_WEIGHT: 0.03 
    BEAM_WIDTH: 1
    
DATASETS:
  TRAIN: ("totaltext_train",)
  TEST: ("totaltext_test",)

SOLVER:
  AMP:
    ENABLED: True  # Enable Automatic Mixed Precision
  IMS_PER_BATCH: 2
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 250
  STEPS: (100000,)  # no step
  MAX_ITER: 2000
  CHECKPOINT_PERIOD: 1000

TEST:
  EVAL_PERIOD: 1000

OUTPUT_DIR: "output/R50/150k_tt_mlt_13_15_textocr/finetune/totaltext"
