_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "output/vitaev2_s/150k_tt_mlt_13_15_textocr/finetune/totaltext/model_0002999.pth"
  ViTAEv2:
    DROP_PATH_RATE: 0.2
  POST_PROCESS:
    ENABLED: True # Set to True to use the LM post-processor with beam search
    LM_PATH: "/home/kylee/DeepSolo/character_lm_enriched_5g.binary" # Path relative to where you run the script, or absolute path
    LM_WEIGHT: 0.3 
    BEAM_WIDTH: 1

DATASETS:
  TRAIN: ("totaltext_train",)
  TEST: ("totaltext_test",)

INPUT:
  MIN_SIZE_TRAIN: (640, 700, 760, 800, 880)
  MAX_SIZE_TRAIN: 1280

SOLVER:
  AMP:
    ENABLED: True  # Enable Automatic Mixed Precision
  IMS_PER_BATCH: 2
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 250
  STEPS: (100000,)
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 1000

TEST:
  EVAL_PERIOD: 1000

OUTPUT_DIR: "output/vitaev2_s/150k_tt_mlt_13_15_textocr/finetune/totaltext"
