_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "output/R50/ctw1500/finetune_maxlen50_96voc/model_0009999.pth"
  TRANSFORMER:
    VOC_SIZE: 96
    NUM_POINTS: 50
    LOSS:
        BEZIER_SAMPLE_POINTS: 50
        BEZIER_CLASS_WEIGHT: 1.0
        BEZIER_COORD_WEIGHT: 0.5
        POINT_CLASS_WEIGHT: 1.0
        POINT_COORD_WEIGHT: 0.5
        POINT_TEXT_WEIGHT: 1.0 #0.5
        BOUNDARY_WEIGHT: 0.25
  POST_PROCESS:
    ENABLED: True # Set to True to use the LM post-processor with beam search
    LM_PATH: "/home/kylee/DeepSolo/character_lm_enriched_5g.binary" # Path relative to where you run the script, or absolute path
    LM_WEIGHT: 0.2 
    BEAM_WIDTH: 1
  
DATASETS:
  TRAIN: ("ctw1500_train_96voc",)
  TEST: ("ctw1500_test",)

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640) # Reduce the upper end of the range
  MAX_SIZE_TRAIN: 1024  # Reduce max size significantly
  ROTATE: False
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 1200

SOLVER:
  AMP:
    ENABLED: True  # Enable Automatic Mixed Precision
  IMS_PER_BATCH: 2
  BASE_LR: 5e-5
  LR_BACKBONE: 5e-6
  WARMUP_ITERS: 0
  STEPS: (8000,)
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 1000

TEST:
  EVAL_PERIOD: 1000

OUTPUT_DIR: "output/R50/ctw1500/finetune_maxlen50_96voc"
